name: papeleria_pv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.4.1
  firebase_analytics: ^11.3.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  auth_buttons: ^3.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  dio: ^5.3.3
  firebase_core_web: ^2.7.0
  cloud_firestore: ^5.2.1
  firebase_database: ^11.0.4
  firebase_storage: ^12.1.3
  flip_card: ^0.7.0
  flutter_native_splash: ^2.3.3
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.4.2
  font_awesome_flutter: ^10.5.0
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  maps_launcher: ^2.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  file_picker: ^8.0.7
  image_picker: ^1.1.2
  image_picker_web: ^2.0.1
  http: ^1.0.0
  badges: ^2.0.2
  intl: ^0.17.0
  firebase_messaging: ^15.1.1
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
